version: '3.8'

services:
  evently-attendee-service:
    build:
      context: ./evently-attendee
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - evently-network

  evently-events-service:
    build:
      context: ./evently-events
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - evently-network

  postgres:
    build: .
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evently
      POSTGRES_USER: evently
      POSTGRES_PASSWORD: evently
    networks:
      - evently-network

networks:
  evently-network:
    driver: bridge
